accounts/urls.py

from .views import *
from django.urls import path

app_name = 'accounts'

urlpatterns = [
     path('register', register_request, name='register'),
     path('login', login_request, name='login'),
     path('logout', logout_request, name='logout'),
     path('user-profile', user_update_request, name='profile'),
]

api/urls.py
from django.urls import path
from .views import *

app_name = 'api'
urlpatterns = [
    path('api-bike/', bikeViewAPI.as_view(), name='bike_list'),
]

accounts/models.py
from django.contrib.auth.models import  AbstractBaseUser, BaseUserManager
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from phone_field import PhoneField

# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError('Email is required.')
        if not first_name:
            raise ValueError('First name is required.')
        if not last_name:
            raise ValueError('Last name is required.')
        if not password:
            raise ValueError('Password is required.')

        user = self.model(
            email = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
        )
        user.set_password(password)
        user.active = is_active
        user.staff = is_staff
        user.admin = is_admin
        user.save(using=self.db)
        return user

    def create_staffuser(self, email, first_name, last_name, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            first_name,
            last_name,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            first_name,
            last_name,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user


class myUser(AbstractBaseUser):
    StayStatus = (
        ('Good', 'Good'),
        ('Needs to receive warning', 'Needs to receive warning'),
        ('Warning already given', 'Warning already given'),
        ('No longer allowed', 'No longer allowed'),
    )
    email = models.EmailField(verbose_name='Email Address', max_length=100, unique=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone = PhoneField(blank=True, null=True)

    active = models.BooleanField(default=True)
    law_enforcement = models.BooleanField(default=False)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']  # Email & Password are required by default.

    objects = UserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def get_full_name(self):
        # The user is identified by their email address
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        # The user is identified by their email address
        if self.first_name and self.last_name:
            return f'{self.first_name}'
        return self.email


    def __str__(self):  # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        #"Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        # "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        #"Is the user a member of staff?"
        return self.staff
    @property
    def is_admin(self):
        #"Is the user a admin member?"
        return self.admin
    @property
    def is_active(self):
        #"Is the user active?"
        return self.active
    @property
    def is_law_enforcement(self):
        #"Is the user active?"
        return self.law_enforcement

#
# not sure if this is the auth style that i want to use
#
#@receiver(post_save, sender=settings.AUTH_USER_MODEL)
#def create_auth_token(sender, instance=None, created=False, **kwargs):
#    if created:
#        Token.objects.create(user=instance)

accounts/forms.py
# main forms
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import myUser

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = myUser
        exclude = ['active', 'staff', 'admin']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = myUser.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email already in use")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = myUser
        fields = ('email', 'first_name', 'last_name')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = myUser
        fields = ('email', 'first_name', 'last_name')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class superUserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = myUser
        fields = '__all__'

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class userProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'autofocus': 'autofocus', 'class': 'validate'})
        self.fields['first_name'].widget.attrs.update({'class': 'validate'})
        self.fields['last_name'].widget.attrs.update({'class': 'validate'})


    class Meta:
        model = myUser
        fields = ['email', 'phone', 'first_name', 'last_name']

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class userCrationForm(UserAdminCreationForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'autofocus': 'autofocus', 'class': 'validate'})
        self.fields['first_name'].widget.attrs.update({'class': 'validate'})
        self.fields['last_name'].widget.attrs.update({'class': 'validate'})
        self.fields['password1'].widget.attrs.update({'class': 'validate'})
        self.fields['password2'].widget.attrs.update({'class': 'validate'})

    class Meta:
        model = myUser
        fields = ('email', 'phone', 'first_name', 'last_name')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render, reverse, redirect, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import *

# Create your views here.

def register_request(request):
    if request.method == 'POST':
        form = userCrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'New user created.')
            return redirect('main:home')
        else:
            messages.error(request, 'Failed to create new user.')
            # return render(request, 'main/Register.html', {'form': form})
    form = userCrationForm()
    return render(request, 'accounts/Register.html', {'form': form})

def login_request(request):
    next = ''
    if request.GET:
        next = request.GET['next']



    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Welcome back, {user.first_name}.')
                if next != '':
                    return redirect(next)
                return redirect('main:home')


        else:
            messages.error(request, 'Invalid username or password')

    form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_request(request):
    logout(request)
    messages.success(request, 'Logout successful.')
    return HttpResponseRedirect(reverse('main:home'))

@login_required()
def user_update_request(request):
    #user is active but not staff
    if request.method == 'POST':
        form = userProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.info(request, 'Your profile has been updated. Thank you.')
            return redirect('main:home')
        else:
            messages.error(request, 'Failed to save update, please correct the form.')
    form = userProfileForm(instance=request.user)
    return render(request, 'accounts/user_profile.html', {'form': form})

accounts/templates/accounts/Register.html
{% extends 'main/base.html' %}


{% block content %}
    <blockquote>Already have an account? <strong><a href="{% url 'accounts:login' %}"> Sign in here.</a></strong></blockquote>
    	<br>
    <p><strong>Passwords are case senitive</strong></p>

    <form method="POST">
        {% csrf_token %}
        <div class="row">
        	<div class="input-field col s12 m6">
		        {% if from.email.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.email.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_email">{{ form.email.label }}:</label>
			        {{ form.email }}
	    	</div>
    		<div class="input-field col s12 m6">
		        {% if from.phone.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.phone.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_phone">{{ form.phone.label }}:</label>
			        <input type="text" name="phone_0" size="4" id="id_phone_0" class="tooltipped" data-html="true" data-position="bottom" data-tooltip="Format: ###-###-####"> <!-- {{ form.phone }} -->
	    	</div>
    	</div>
        <div class="row">
        	<div class="input-field col s12 m6">
		        {% if from.first_name.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.first_name.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}

			        <label for="id_first_name">{{ form.first_name.label }}:</label>
			        {{ form.first_name }}
	    	</div>

        	<div class="input-field col s12 m6">
		        {% if from.last_name.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.last_name.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}

			        <label for="id_last_name">{{ form.last_name.label }}:</label>
			        {{ form.last_name }}
	    	</div>
    	</div>
   
        <div class="row">
        	<div class="input-field col s12">
		        {% if from.password.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.password1.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_password">{{ form.password1.label }}:</label>
			        <input class="tooltipped validate invalid" data-html="true" data-position="bottom" data-tooltip="<ul><li>Your password can't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can't be a commonly used password.</li><li>Your password can't be entirely numeric.</li></ul>" type="password" name="password1" required="" id="id_password1"><!--  {{ form.password1 }} -->
	    	</div>
    	</div>
        <div class="row">
        	<div class="input-field col s12">
		        {% if from.password2.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.password2.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_password">{{ form.password2.label }}:</label>
			        <input type="password" name="password2" class="validate invalid tooltipped" required="" id="id_password2" data-html="true" data-position="bottom" data-tooltip="Password Confirmation must match previous password field exactly."> <!-- {{ form.password2 }} -->
	    	</div>
    	</div>
        <button class="waves-effect waves-light btn" type="submit" name="Submit">Save</button>
    </form>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'main/base.html' %}

{% block content %}
    <blockquote>Don't have an account? <strong><a href="{% url 'accounts:register' %}"> Create one here.</a></strong></blockquote>
    	<br>

	{% if next %}
		<form action="/?next={{next}}" method="post" >
	{%else%}
		<form method="post" >
	{% endif %}
        {% csrf_token %}
        <p><strong>Email and Passwords are case senitive</strong></p>
        <div class="row">
        	<div class="input-field col s12">
		        {% if from.username.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.username.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
		        <label for='id_username'> {{ form.username.label }}: </label>
		        {{ form.username }}
		    </div>
		    <div class="input-field col s12">
		        {% if from.password.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.password.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
		        <label for='id_password'> {{ form.password.label }}: </label>
		        {{ form.password }}
		    </div>
	    </div>
        <button class="waves-effect waves-light btn" type="submit" name="Submit"><i class="material-icons right">save</i>Submit</button>
    </form>


{% endblock %}

accounts/templates/accounts/user_profile.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="row">
        	<div class="input-field col s12">
		        {% if from.email.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.email.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_email">{{ form.email.label }}:</label>
			        {{ form.email }}
	    	</div>
    	<div class="input-field col s12">
		        {% if from.phone.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.phone.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_phone">{{ form.phone.label }}:</label>
					{{ form.phone }}
	    	</div>
    	</div>

        <div class="row">
        	<div class="input-field col s12 m6">
		        {% if from.first_name.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.first_name.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}

			        <label for="first_name">{{ form.first_name.label }}:</label>
			        {{ form.first_name }}
	    	</div>

        	<div class="input-field col s12 m6">
		        {% if from.last_name.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.last_name.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}

			        <label for="id_last_name">{{ form.last_name.label }}:</label>
			        {{ form.last_name }}
	    	</div>
    	</div>
    	
    	<div class="row">
    		<div class="input-field col s12 m6">
    					        {% if from.state.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.state.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_state">{{ form.state.label }}:</label>
			        {{ form.state }}
    		</div>
    		<div class="input-field col s12 m6">
    					        {% if from.city.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.city.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_city">{{ form.city.label }}:</label>
			        {{ form.city }}
    		</div>
    	</div>
        <!-- <div class="row">
        	<div class="col s12">
		        {% if from.password.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.password1.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_password">{{ form.password1.label }}:</label>
			        <span class="tooltipped" data-html="true" data-position="bottom" data-tooltip="<ul><li>Your password can't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can't be a commonly used password.</li><li>Your password can't be entirely numeric.</li></ul>">{{ form.password1 }}</span>
	    	</div>
    	</div>
        <div class="row">
        	<div class="col s12">
		        {% if from.password2.errors %}
		        	<ul class="errorlist">
		        		{% for error in from.password2.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			        <label for="id_password">{{ form.password2.label }}:</label>
			        <span class="tooltipped" data-html="true" data-position="bottom" data-tooltip="Password Confirmation must match previous password field exactly.">{{ form.password2 }}</span>
	    	</div>
    	</div> -->
        <button class="waves-effect waves-light btn" type="submit" name="Submit">Save</button>
    </form>

{% endblock %}