api/urls.py
from django.urls import path
from .views import *

app_name = 'api'
urlpatterns = [
    path('api-bike/', bikeViewAPI.as_view(), name='bike_list'),
]

bikes/urls.py

from .views import *
from django.urls import path

app_name = 'bikes'

urlpatterns = [
    path('create', bike_create, name='create'),
    path('delete/<int:pk>', BikeDelete.as_view(), name='delete'),
    path('<str:username>', bike_list, name='list'),
    path('<str:username>/<str:serial_number>', bike_detail, name='detail'),
    path('lost', lost_bikes, name='lost')
]

bikes/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse


def user_directory_path(instance, filename):
    return f'media/uploads/user_{instance.owner.id}/{filename}'


class bike(models.Model):

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    bike_brand = models.CharField(max_length=50, blank=True, null=True)
    bike_model = models.CharField(max_length=50, blank=True, null=True)
    bike_serial_number = models.CharField(max_length=20)
    bike_image1 = models.ImageField(upload_to='media/', blank=True, null=True, help_text='Suggested: image of the Serial Number')
    bike_image2 = models.ImageField(upload_to='media/', blank=True, null=True, help_text='Suggested: image of the bike from the side with owner')
    bike_image3 = models.ImageField(upload_to='media/', blank=True, null=True, help_text='Suggested: image highlighting any after market features')
    bike_stolen = models.BooleanField(default=False)
    
    def __str__(self):
        if self.bike_brand:
            return f'{self.bike_serial_number}, {self.bike_brand}'
        return self.bike_serial_number

    def get_absolute_url(self):
        return reverse('bikes:detail', kwargs={'username': self.owner.email, 'serial_number': self.bike_serial_number})

bikes/forms.py
from django import forms
from .models import bike


class BikeForm(forms.ModelForm):
    class Meta:
        model = bike
        fields = [
            'owner',
            'bike_brand',
            'bike_model',
            'bike_serial_number',
            'bike_stolen',
            'bike_image1',
            'bike_image2',
            'bike_image3',
        ]
        # widgets = {'owner': forms.TextInput(attrs={'disabled': True, 'hidden': True})}
        widgets = {'owner': forms.HiddenInput()}
        # widgets = {'owner': forms.TextInput()}



bikes/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView


from .forms import BikeForm
from .models import bike


@login_required()
def bike_create(request):
    if request.POST:
        form = BikeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Input saved')
            return redirect('bikes:list', username=request.user.email)
    form = BikeForm()
    return render(request, 'bikes/bike_create.html', {'form': form})


class BikeDelete(DeleteView):
    model = bike

    def get_success_url(self):
        email = self.object.owner.email
        return reverse_lazy('bikes:list', kwargs={'username': email})


@login_required()
def bike_list(request, username):
    my_bikes = bike.objects.filter(owner__email=username)
    context = {
        'bikes': my_bikes,
    }
    return render(request, 'bikes/bike_list.html', context)


@login_required()
def bike_detail(request, username, serial_number):
    instance = get_object_or_404(bike, owner__email=username, bike_serial_number=serial_number)
    if request.POST:
        form = BikeForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            messages.success(request, 'Input saved')
            return redirect('bikes:list', username=request.user.email)
    form = BikeForm(instance=instance)
    return render(request, 'bikes/bike_detail.html', {'form': form, 'bike': instance})

def lost_bikes(request):
    stolen_bikes = bike.objects.get().filter(bike_stolen=True)
    context = {'bikes': stolen_bikes}
    return render(request, 'bikes/bike_stolen.html', context)

# def bikeDetail1(request):
#
#     if request.method == 'POST':
#         form = bikeForm(request, request.POST)
#         form.data['owner'] = request.user.id
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Bike saved successfully.')
#             return redirect('bike:bike_list')
#
#         else:
#             messages.error(request, 'Invalid data, please retry.')
#
#     form = bikeForm()
#     return render(request, 'bikes/bike_detail.html', {'form': form})

bikes/templates/bikes/BikeCreate_form.html
{% extends 'main/base.html' %}
{% block stolen %}
{% endblock stolen%}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

bikes/templates/bikes/bike_confirm_delete.html
{% extends 'main/base.html' %}
{% block stolen %}
{% endblock stolen%}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button class="waves-effect waves-light btn red" type="submit" name="Submit">Confirm</button>
</form>
{% endblock %}

bikes/templates/bikes/bike_create.html
{% extends 'main/base.html' %}
{% block stolen %}
{% endblock stolen%}

{% block content %}
{% load materializecss %}
<div class="container">
<form>
	<label for='id_owner'> {{ form.owner.label }} </label> 
	<input disabled type="text" name="" value="{{ user.email }}"> 
</form>
	<form method="post" enctype='multipart/form-data'>{% csrf_token %}	
		<div class="row">
				<input type="hidden" name="owner" id="id_owner" value="{{ user.id }}">
				{{ form.bike_brand|materializecss:'s12 m4' }}
				{{ form.bike_brand|materializecss:'s12 m4' }}
		    	{{ form.bike_serial_number|materializecss:'s12 m4' }}
		</div>
		<div class="row">
		        {{ form.bike_image1|materializecss:'s12 m4' }}
		        {{ form.bike_image2|materializecss:'s12 m4' }}
		        {{ form.bike_image3|materializecss:'s12 m4' }}
		</div>
        <button class="waves-effect waves-light btn" type="submit" name="Submit"><i class="material-icons right">save</i>Submit</button>
    </form>
</div>
{% endblock %}

bikes/templates/bikes/bike_create_backup.html
{% extends 'main/base.html' %}
{% block stolen %}
{% endblock stolen%}


{% block content %}
<form>
	<label for='id_owner'> {{ form.owner.label }}: </label> 
	<input disabled type="text" name="" value="{{ user.email }}"> 
</form>
	<form method="post" enctype='multipart/form-data'>{% csrf_token %}	
		<div class="row">
				<input type="hidden" name="owner" id="id_owner" value="{{ user.id }}">
			<div class="input-field col s12 m3 l4">
		        {% if form.bike_brand.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_brand.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
 				<label for='id_username'> {{ form.bike_brand.label }}: </label>  
		        {{ form.bike_brand }}
		    </div>
			<div class="input-field col s12 m3 l4">
		        {% if form.bike_model.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_model.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
 				<label for='id_username'> {{ form.bike_model.label }}: </label> 
		        {{ form.bike_model }}
		    </div>
		    <div class="input-field col s12 m3 l4">
		        {% if form.bike_serial_number.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_serial_number.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}

 				<label for='id_username'> {{ form.bike_serial_number.label }}: </label>
		        {{ form.bike_serial_number }}
		    </div>
		</div>
		<div class="row">
			<div class="input-field col s12 m3 l4">
		        {% if form.bike_image1.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_image1.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %} 
		        {{ form.bike_image1 }}
		    </div>

			<div class="input-field col s12 m3 l4">
		        {% if form.bike_image2.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_image2.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
		        {{ form.bike_image2 }}
		    </div>

			<div class="input-field col s12 m3 l4">
		        {% if form.bike_image3.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_image3.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
		        {{ form.bike_image3 }}
		    </div>
		</div>
        <button class="waves-effect waves-light btn" type="submit" name="Submit"><i class="material-icons right">save</i>Submit</button>
    </form>

{% endblock %}








<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

bikes/templates/bikes/bike_detail.html
{% extends 'main/base.html' %}
{% block stolen %}
{% endblock stolen%}

{% block content %}
{% load materializecss %}
<div class="container">
	<form>
		<div class="row">
			<div class="input-field col s12 m6">
 				<label for="owner">Owner:</label>
				<input disabled id="owner" type="text" value="{{ bike.owner.email }}">
		    </div>
			<div class="input-field col s12 m6">
				<label for="Created">Created On:</label>
				<input disabled id="Created" type="text" value="{{ bike.created_on }}">
			</div>
		</div>
	</form>
	<form method="post" enctype='multipart/form-data'>{% csrf_token %}	
		<div class="row">
			{{ form.owner }} 
	        {{ form.bike_brand|materializecss:'s12 m4' }} 
	        {{ form.bike_model|materializecss:'s12 m4' }}
		    {{ form.bike_serial_number|materializecss:'s12 m4' }}
		    {{ form.bike_stolen|materializecss:'s12 m4' }}
		</div>
		<br>
		<div class="row">
			<div class="input-field col s12 m4">
				{% if bike.bike_image1 %}
					<img class="responsive-img materialboxed" src="{{ bike.bike_image1.url }}">
				{% endif %} 
		    </div>

			<div class="input-field col s12 m4">
				{% if bike.bike_image2 %}
					<img class="responsive-img materialboxed" src="{{ bike.bike_image2.url }}">
				{% endif %} 
		    </div>

			<div class="input-field col s12 m4">
				{% if bike.bike_image3 %}
					<img class="responsive-img materialboxed" src="{{ bike.bike_image3.url }}">
				{% endif %} 
		    </div>
		</div>
		<div class="row">
		        {{ form.bike_image1|materializecss:'s12 m4' }}
		        {{ form.bike_image2|materializecss:'s12 m4' }}
		        {{ form.bike_image3|materializecss:'s12 m4' }}
		</div>
		<br><br>
		<div class="row">
        	<button class="waves-effect waves-light btn" type="submit" name="Submit"><i class="material-icons right">save</i>Submit</button>
    	</div>
    </form>
</div>
{% endblock %}

bikes/templates/bikes/bike_detail_backup.html
{% extends 'main/base.html' %}
{% block stolen %}
{% endblock stolen%}

{% block content %}
{% load materializecss %}
	<form>
		<div class="row">
			<div class="input-field col s12 m6">
 				<label for="owner">Owner:</label>
				<input disabled id="owner" type="text" value="{{ bike.owner.email }}">
		    </div>
			<div class="input-field col s12 m6">
				<label for="Created">Created On:</label>
				<input disabled id="Created" type="text" value="{{ bike.created_on }}">
			</div>
		</div>
	</form>
	<form method="post" enctype='multipart/form-data'>{% csrf_token %}	
		<div class="row">
			{{ form.owner }}
			<div class="input-field col s12 m6 l4">
		        {% if form.bike_brand.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_brand.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
 				<label for='id_username'> {{ form.bike_brand.label }}: </label> 
		        {{ form.bike_brand }}
		    </div>
			<div class="input-field col s12 m6 l4">
		        {% if form.bike_model.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_model.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
 				<label for='id_username'> {{ form.bike_model.label }}: </label>  
		        {{ form.bike_model }}
		    </div>
		    <div class="input-field col s12 m6 l4">
		        {% if form.bike_serial_number.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_serial_number.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
 				<label for='id_username'> {{ form.bike_serial_number.label }}: </label>   
		        {{ form.bike_serial_number }}
		    </div>
		    <div class="input-field col s12 m6 l4">
		        {% if form.bike_stolen.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_stolen.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
			    <label>
					{{ form.bike_stolen }}
					<!-- <input type="checkbox" name="bike_stolen" id="id_bike_stolen"> -->
					<span>{{ form.bike_stolen.label }}</span>
				</label>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="input-field col s12 m6 l4">
		        {% if form.bike_image1.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_image1.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
				{% if bike.bike_image1 %}
					<img class="responsive-img materialboxed" src="{{ bike.bike_image1.url }}">
				{% endif %} 
		        {{ form.bike_image1 }}
		    </div>

			<div class="input-field col s12 m6 l4">
		        {% if form.bike_image2.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_image2.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
				{% if bike.bike_image2 %}
					<img class="responsive-img materialboxed" src="{{ bike.bike_image2.url }}">
				{% endif %} 
		        {{ form.bike_image2 }}
		    </div>

			<div class="input-field col s12 m6 l4">
		        {% if form.bike_image3.errors %}
		        	<ul class="errorlist">
		        		{% for error in form.bike_image3.errors %}
		        			<li>{{ error }}</li>
		    			{% endfor %}
		        	</ul>
		        {% endif %}
				{% if bike.bike_image3 %}
					<img class="responsive-img materialboxed" src="{{ bike.bike_image3.url }}">
				{% endif %} 
		        {{ form.bike_image3 }}
		    </div>
		</div>
        <button class="waves-effect waves-light btn" type="submit" name="Submit"><i class="material-icons right">save</i>Submit</button>
    </form>

{% endblock %}

bikes/templates/bikes/bike_list.html
{% extends 'main/base.html' %}

{% block stolen %}
{% endblock stolen%}


{% block content %}
	<div class="row">
		{% for bike in bikes %}
			<div class="col s12 m6">
				<div class="card">
					<div class="card-image">
						{% if bike.bike_image1 %}
							<img src="{{ bike.bike_image1.url }}">
						{% endif %}
						<span class="card-title">{% if bike.bike_brand%} {{ bike.bike_brand }} {% endif %}</span>
					</div>
					<div class="card-content">
						<p>{{ bike.bike_serial_number }}</p>
						<p>{{ user.email }}</p>
					</div>
					<div class="card-action">
						<a href="{{ bike.get_absolute_url }}">Details</a>
						<a href="{% url 'bikes:delete' bike.id %}">Delete</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	<div class="fixed-action-btn">
		<a href="{% url 'bikes:create' %}" class="btn-floating btn-large teal">
			<i class="large material-icons">add</i>
		</a>
	</div>
{% endblock %}



bikes/templates/bikes/bike_stolen.html
{% extends 'main/base.html' %}

{% block content %}
	<div class="row">
		{% for bike in bikes %}
			<div class="col s12 m6">
				<div class="card">
					<div class="card-image">
						{% if bike.bike_image1 %}
							<img src="{{ bike.bike_image1.url }}">
						{% endif %}
						<span class="card-title">{% if bike.bike_brand%} {{ bike.bike_brand }} {% endif %}</span>
					</div>
					<div class="card-content">
						<p>{{ bike.bike_serial_number }}</p>
						<p>{{ user.email }}</p>
					</div>

				</div>
			</div>
		{% endfor %}
	</div>
	<div class="fixed-action-btn">
		<a href="{% url 'bikes:create' %}" class="btn-floating btn-large teal">
			<i class="large material-icons">add</i>
		</a>
	</div>
{% endblock %}

