accounts/urls.py

from .views import *
from django.urls import path

app_name = 'accounts'

urlpatterns = [
     path('register', register_request, name='register'),
     path('login', login_request, name='login'),
     path('logout', logout_request, name='logout'),
     path('user-profile', user_update_request, name='profile'),
]

api/urls.py
from django.urls import path
from .views import *

app_name = 'api'
urlpatterns = [
    path('api-bike/', bikeViewAPI.as_view(), name='bike_list'),
]

bikes/urls.py

from .views import *
from django.urls import path

app_name = 'bikes'

urlpatterns = [
    path('create', bike_create, name='create'),
    path('delete/<int:pk>', BikeDelete.as_view(), name='delete'),
    path('<str:username>', bike_list, name='list'),
    path('<str:username>/<str:serial_number>', bike_detail, name='detail'),
    path('lost', lost_bikes, name='lost')
]

main/urls.py

from .views import *
from django.urls import path

app_name = 'main'

urlpatterns = [
     path('', index, name='home'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'main/base.html', {})

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
	{% block css %}
	  <!-- Compiled and minified CSS -->
	  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	  <!-- icons -->
	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
	{% endblock css %}
	
	{% block pageCSS%}
	    <style type="text/css">
	    	.errorlist {
	  			color: red;
	  			font-weight: bold;
			}
			.phone-field-ext { display: none; }
			#id_phone_1 { display: none; }
	    </style>
	{% endblock pageCSS%}

            
  <title>Bike Registry</title>
</head>

<body class="grey lighten-5">


	{% include "main/navBar.html" %}
	{% include "main/messages.html" %}	
	<br>

	{% block stolen %}
		<div class="row">
				<div class="container col s12 m3 white">
					<div id="stolen_bikes">
						<h3>Reported stolen:</h3>
					</div>
				</div>
				<div class="col s12 m1"><br></div>
	{% endblock %}	
		<div class="container col s12 m7 white">
			{% block content %}
			<h1>Hi all,</h1>
			<p>There is a lot of development still to do on this site. The basics are here and working, if you find something that needs improvments please let me know.</p>
			{% endblock content %}
		</div>	

		<br><br>
	</div>		
	<div class="row">
		<div class="footer grey lighten-3 col s12">
			<span class="right">{% block footer %}
				
			{% endblock footer %}</span>
			<br>
		</div>
	</div>

	{% block javascript %}
		<script
		  src="https://code.jquery.com/jquery-3.3.1.min.js"
		  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
		  crossorigin="anonymous"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

		<script>
		$(document).ready(function(){

		  // Initialize materialize data picker
		  $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
		  $('select').formSelect();

		});
		</script>
	{% endblock javascript %}
    
		{% block script %}
		
		{% endblock script %}
    <script>
		document.addEventListener('DOMContentLoaded', function() {
    		var elems = document.querySelectorAll('.sidenav');
    		var instances = M.Sidenav.init(elems, );
		});

		document.addEventListener('DOMContentLoaded', function() {
			var elems = document.querySelectorAll('.dropdown-trigger');
			var instances = M.Dropdown.init(elems, {
				coverTrigger: false,
				hover: true,
			});
		});

		M.AutoInit();

    	$(function (){
	    	var $bikes = $('#stolen_bikes')
	    	$.ajax({
	    		type: 'GET',
	    		url: 'api/api-bike',
	    		success: function(bikes) {
	    			$.each(bikes, function(i, bike){
	    				console.log(bike)
	    				var image = bike.bike_image1
	    				var brand = bike.bike_brand
	    				var model = bike.bike_model
	    				console.log(model)
	    				$bikes.append('<div class="card"><div class="card-image"><img src="'+image+'"><span class="card-title"></span></div><div class="card-content">'+(brand == null ? ' ': '<p>Brand: '+brand+'</p>')+(model == null ? ' ': '<p>Model: '+model+'</p>')+'<p>Serial Number: '+bike.bike_serial_number+'</p></div><div class="card-action"><a class="btn-floating waves-effect waves-light blue" href="mailto:'+bike.owner.email+'"><i class="material-icons">email</i></a></div></div>')
	    			});
	    		}
	    	});
	    });
	</script>
</body>
</html>

main/templates/main/baseBackUp.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
<!--     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script> -->
    <!-- custom styles -->
    <style type="text/css">
    	.errorlist {
  			color: red;
  			font-weight: bold;
		}
		.phone-field-ext { display: none; }
		#id_phone_1 { display: none; }
    </style>
            
  <title>Bike Registry</title>
</head>

<body class="grey lighten-5">
	{% include "main/navBar.html" %}
	{% include "main/messages.html" %}	
	<br>

	{% block stolen %}
		<div class="row">
				<div class="container col s12 m3 white">
					<div id="stolen_bikes">
						<h3>Reported stolen:</h3>
					</div>
				</div>
				<div class="col s12 m1"><br></div>
	{% endblock %}	
		<div class="container col s12 m7 white">
			{% block content %}
			<h1>Hi all,</h1>
			<p>There is a lot of development still to do on this site. The basics are here and working, if you find something that needs improvments please let me know.</p>
			{% endblock content %}
		</div>	

		<br><br>
	</div>		
	<div class="row">
		<div class="footer grey lighten-3 col s12">
			<span class="right">{% block footer %}
				
			{% endblock footer %}</span>
			<br>
		</div>
	</div>

	<!--JavaScript at end of body for optimized loading-->
	<!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>

    
		{% block script %}
		
		{% endblock script %}
    <script>
		document.addEventListener('DOMContentLoaded', function() {
    		var elems = document.querySelectorAll('.sidenav');
    		var instances = M.Sidenav.init(elems, );
		});

		document.addEventListener('DOMContentLoaded', function() {
			var elems = document.querySelectorAll('.dropdown-trigger');
			var instances = M.Dropdown.init(elems, {
				coverTrigger: false,
				hover: true,
			});
		});

		M.AutoInit();

    	$(function (){
	    	var $bikes = $('#stolen_bikes')
	    	$.ajax({
	    		type: 'GET',
	    		url: 'api/api-bike',
	    		success: function(bikes) {
	    			$.each(bikes, function(i, bike){
	    				console.log(bike)
	    				$bikes.append('<div class="card"><div class="card-image"><img src="'+bike.bike_image1+'"><span class="card-title"></span></div><div class="card-content"><p>Brand: '+bike.bike_brand+'</p><p>Model: '+bike.bike_model+'</p><p>Serial Number: '+bike.bike_serial_number+'</p></div><div class="card-action"><a class="btn-floating waves-effect waves-light blue" href="mailto:'+bike.owner.email+'"><i class="material-icons">email</i></a></div></div>')
	    			});
	    		}
	    	});
	    });
	</script>
</body>
</html>

main/templates/main/blogpost_confirm_delete.html
{% extends 'main/base.html' %}

{% block pageTitle %}
	Site Type
{% endblock pageTitle %}

{% block content %}
	<form method="post" name="my_form"> {% csrf_token %}
		<p>Are you sure you want to delete "{{ object }}"?</p>
		<button class="waves-effect waves-light btn red" type="submit" name="Save"><i class="material-icons right">save</i>Save</button>
	</form>
{% endblock content %}

main/templates/main/blogpost_create.html
{% extends 'main/base.html' %}

{% block pageTitle %}
	{{ object.title | title}}
{% endblock pageTitle %}


{% block content %}
	<form method="post" name="blogPost_update_form"> {% csrf_token %}
		<div class="row">
			<div class="col s12 m6">
				{{form.title.label}} {{ form.title }}
			</div>
			<div class="col s12 m6">
				{{form.publish_date.label}} {{ form.publish_date }}
			</div>
		</div>
		<div class="row">
			<div class="col s12">
				{{form.post.label}} {{ form.post }}
			</div>
			
		</div>
		
		
		<button class="waves-effect waves-light btn" type="submit" name="Save"><i class="material-icons right">save</i>Save</button>
	</form>
{% endblock content %}

main/templates/main/blogpost_detail.html
{% extends 'main/base.html' %}

{% block pageTitle %}
	{{ object.title | title}}
{% endblock pageTitle %}

{% block content %}
	<div class="row">
		<div class="col s12">
			<p>{{ object.post | linebreaks }}</p>
		</div>
	</div>
	<div class="row">
		<div class="divider"></div>
		<div class="row">
			<div class="col s12 m6">
        		<div class="card-panel grey lighten-5 z-depth-1">
				 	<i class="material-icons tiny">date_range</i> 
				 	Published: {{ object.publish_date }}
				</div>
			</div>
			{% if user.is_staff %}
				<div class="col s12 m6">
        			<div class="card-panel grey lighten-5 z-depth-1">
						Auther: {{object.author}}
					</div>
				</div>
			{% endif %}
		</div>
	</div>

{% endblock content %}

{% block footer %}
<a href="{% url 'main:home' %}">Back</a>
{% endblock footer %}

main/templates/main/blogpost_form.html
{% extends 'main/base.html' %}

{% block pageTitle %}
	{{ object.title | title}}
{% endblock pageTitle %}


{% block content %}
	<form method="post" name="blogPost_update_form"> {% csrf_token %}
		<div class="row">
			<div class="col s12 m6">
				{{form.title.label}} {{ form.title }}
			</div>
			<div class="col s12 m6">
				{{form.publish_date.label}} {{ form.publish_date }}
			</div>
		</div>
		<div class="row">
			<div class="col s12">
				{{form.post.label}} {{ form.post }}
			</div>
			
		</div>
		
		
		<button class="waves-effect waves-light btn" type="submit" name="Save"><i class="material-icons right">save</i>Save</button>
	</form>
{% endblock content %}

main/templates/main/confirm_delete.html
{% extends 'main/base.html' %}

{% block pageTitle %}
	{{ title }}
{% endblock pageTitle %}

{% block content %}
	<form method="post" name="my_form"> {% csrf_token %}
		<p>Are you sure you want to delete "{{ object }}"?</p>
		{% if object.check_in %}
			<p> Reservation for {{ object.check_in }} to {{ object.check_out }}
			</p>
		{% endif %}
		<button class="waves-effect waves-light btn red" type="submit" name="Save"><i class="material-icons right">save</i>Save</button>
	</form>
{% endblock content %}

main/templates/main/messages.html
{% if messages %}
	<ul class="messages">
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:3000});</script>
        {% elif message.tags == 'info' %}
            <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:4000});</script>
        {% elif message.tags == 'warning' %}
            <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:5000});</script>
        {% elif message.tags == 'error' %}
            <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:5000});</script>
        {% endif %}
    {% endfor %}
    </ul>
{% endif %}

main/templates/main/navBar.html

<!-- side Nav -->
<ul id="slide-out" class="sidenav">
    <li>
  		<a class="waves-effect" href="{% url 'main:home' %}" class="brand-logo waves-effect"><strong>Bike Registry</strong></a>
  	</li>
	{% if user.is_authenticated %}
		<li><a class="waves-effect" href="{% url 'accounts:profile' %}">{{ user.email }}</a></li>
		<li><a class="waves-effect" href="{% url 'accounts:logout' %}">Logout</a></li>
		<li><a class="waves-effect" href="{% url 'bikes:list' user.email %}">My Bikes</a></li>
	{% else %}
		<li><a class="waves-effect" href="{% url 'accounts:register' %}">Sign Up</a></li>
		<li><a class="waves-effect" href="{% url 'accounts:login' %}">Login</a></li>
	{% endif %}

	<li><div class="divider"></div></li>	

	{% if user.is_staff %}
	<li><a class="waves-effect" href="/admin">Admin</a></li>
	{% endif %}
</ul>	


<!-- main Nav Bar -->
<div class="navbar">
	<nav>
		<div class="nav-wrapper teal lighten-2">
			<div class="container">
				<a href="{% url 'main:home' %}" class="brand-logo waves-effect">Bike Registry</a>
				<a href="#" data-target="slide-out" class="sidenav-trigger show-on-small show-on-med"><i class="material-icons">menu</i></a>
				<ul id="nav-mobile" class="right hide-on-med-and-down">
					{% if user.is_authenticated %}
						<li class="waves-effect"><a href="{% url 'accounts:profile' %}">{{ user.email }}</a></li>
						<li><a class="waves-effect" href="{% url 'bikes:list' user.email %}">My Bikes</a></li>
						<li class="waves-effect"><a href="{% url 'accounts:logout' %}">Logout</a></li>
					{% else %}
						<li class="waves-effect"><a href="{% url 'accounts:register' %}">Sign Up</a></li>
						<li class="waves-effect"><a href="{% url 'accounts:login' %}">Login</a></li>
					{% endif %}
					{% if user.is_staff %}
						<li><a class="waves-effect" href="/admin">admin</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>   
</div>	


<!-- javaScript -->

main/templates/main/navBarMatirialize.html

<!-- side Nav -->
<ul id="slide-out" class="sidenav">
    <li>
  		<a class="waves-effect" href="{% url 'main:home' %}" class="brand-logo waves-effect"><strong>Bike Registry</strong></a>
  	</li>
	{% if user.is_authenticated %}
		<li><a class="waves-effect" href="{% url 'accounts:profile' %}">{{ user.email }}</a></li>
		<li><a class="waves-effect" href="{% url 'accounts:logout' %}">Logout</a></li>
		<li><a class="waves-effect" href="{% url 'bikes:list' user.email %}">My Bikes</a></li>
	{% else %}
		<li><a class="waves-effect" href="{% url 'accounts:register' %}">Sign Up</a></li>
		<li><a class="waves-effect" href="{% url 'accounts:login' %}">Login</a></li>
	{% endif %}

	<li><div class="divider"></div></li>	

	{% if user.is_staff %}
	<li><a class="waves-effect" href="/admin">Admin</a></li>
	{% endif %}
</ul>	


<!-- main Nav Bar -->
<div class="navbar">
	<nav>
		<div class="nav-wrapper teal lighten-2">
			<div class="container">
				<a href="#" data-target="slide-out" class="sidenav-trigger show-on-small show-on-med"><i class="material-icons">menu</i></a>
				<a href="{% url 'main:home' %}" class="brand-logo waves-effect">Bike Registry</a>
				<ul id="nav-mobile" class="right hide-on-med-and-down">
					{% if user.is_authenticated %}
						<li class="waves-effect"><a href="{% url 'accounts:profile' %}">{{ user.email }}</a></li>
						<li><a class="waves-effect" href="{% url 'bikes:list' user.email %}">My Bikes</a></li>
						<li class="waves-effect"><a href="{% url 'accounts:logout' %}">Logout</a></li>
					{% else %}
						<li class="waves-effect"><a href="{% url 'accounts:register' %}">Sign Up</a></li>
						<li class="waves-effect"><a href="{% url 'accounts:login' %}">Login</a></li>
					{% endif %}
					{% if user.is_staff %}
						<li><a class="waves-effect" href="/admin">admin</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>   
</div>	


<!-- javaScript -->

main/templates/main/navBar_blog.html

<!-- side Nav -->
<ul id="slide-out" class="sidenav">
    <li>
  		<a class="waves-effect" href="{% url 'main:home' %}" class="brand-logo waves-effect"><strong>Bike Registry</strong></a>
  	</li>
	{% if user.is_authenticated %}
		<li><a class="waves-effect" href="{% url 'accounts:profile' %}">{{ user.email }}</a></li>
		<li><a class="waves-effect" href="{% url 'accounts:logout' %}">Logout</a></li>
	{% else %}
		<li><a class="waves-effect" href="{% url 'accounts:register' %}">Sign Up</a></li>
		<li><a class="waves-effect" href="{% url 'accounts:login' %}">Login</a></li>
	{% endif %}

	<li><div class="divider"></div></li>	

	{% if user.is_staff %}
	<li>
		<ul>
          <li>
            <a class="collapsible-header">Posts<i class="material-icons right">arrow_drop_down</i></a>
            <div class="collapsible-body grey lighten-2">
              <ul>
				  <li><a href="{% url 'main:post_create' %}">Create</a></li>
				  <li><a href="{% url 'main:home' %}">Published</a></li>
				  <li><a href="{% url 'main:scheduled' %}">Scheduled</a></li>
              </ul>
            </div>
          </li>
        </ul>
	</li>
	<li><div class="divider"></div></li>	
	<li class="no-padding grey lighten-1">
        <ul class="collapsible collapsible-accordion">
          <li>
            <a class="collapsible-header">Sites<i class="material-icons right">arrow_drop_down</i></a>
            <div class="collapsible-body grey lighten-2">
              <ul>
                <li><a href="{% url 'sitemanager:site_list' %}">Sites</a></li>
                <li><a href="{% url 'sitemanager:section_list' %}">Sections</a></li>
                <li><a href="{% url 'sitemanager:site_type_list' %}">Types</a></li>
              </ul>
            </div>
          </li>
        </ul>
	</li>
	<li><a class="waves-effect" href="/admin">Admin</a></li>
	{% endif %}
</ul>	


<!-- main Nav Bar -->
<div class="navbar-fixed">
	<nav>
		<div class="nav-wrapper teal lighten-2">
			<div class="container">
				<a href="#" data-target="slide-out" class="sidenav-trigger show-on-small show-on-med"><i class="material-icons">menu</i></a>
				<a href="{% url 'main:home' %}" class="brand-logo waves-effect">Bike Registry</a>
				<ul id="nav-mobile" class="right hide-on-med-and-down">
					{% if user.is_authenticated %}
						<li class="waves-effect"><a href="{% url 'accounts:profile' %}">{{ user.email }}</a></li>
						<li class="waves-effect"><a href="{% url 'accounts:logout' %}">Logout</a></li>
					{% else %}
						<li class="waves-effect"><a href="{% url 'accounts:register' %}">Sign Up</a></li>
						<li class="waves-effect"><a href="{% url 'accounts:login' %}">Login</a></li>
					{% endif %}
					{% if user.is_staff %}
						<li><a class="waves-effect" href="/admin">admin</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>   
</div>	


<!-- javaScript -->

main/templates/main/post_list.html
{% extends 'main/base.html' %}



{% block content %}
	{% if object_list %}
		<div class="row">
			{% for object in object_list %}
					<div class="col s12">
						<div class="card hover">
							<a href="{% url 'main:post_detail' object.slug %}">
								<div class="card-content black-text">
									<span class="btn teal white-text">{{ object.publish_date }}</span>
									<span class="card-title center"><strong>{{ object.title|title}}</strong></span>
									<p>{{ object.post | linebreaks | truncatewords:20 }}</p>
								</div>
							</a>
							<div class="card-action teal lighten-2">
								{% if user.is_staff %}
									<a class="white-text" href="{% url 'main:post_update' object.slug %}">Edit</a>
									<a class="white-text" href="{% url 'main:post_delete' object.slug %}">Delete</a>
								{% endif %}
							</div>
						</div>
					</div>
			{% endfor %}
		</div>
	{% else %}
		{% lorem 12 p random %}
	{% endif %}
{% endblock content %}